const int NUMBER_OF_ELEMENTS = 252;
const int MAX_SIZE = 140;

char birdFacts [NUMBER_OF_ELEMENTS] [MAX_SIZE] = {
{"The Orange-headed Thrush is a songbird with striking orange and black plumage"}, 
{"The Red-billed Firefinch has bright red plumage and is found in sub-Saharan Africa"}, 
{"The Long-tailed Jaeger is a seabird known for its agile flight and long, pointed tail"}, 
{"The Chestnut-mandibled Toucan has a large, colourful bill and is found in Central and South America"}, 
{"The Blue-winged Teal is a dabbling duck with striking blue wing patches"}, 
{"The Eurasian Greenfinch has a distinctive, twittering song and is found in Europe, Asia, and North Africa"}, 
{"The Red-faced Warbler has vibrant red plumage on its face and is found in North America"}, 
{"The White-cheeked Tern is known for its elegant flight and plunging dives for fish"}, 
{"The Pin-tailed Sandgrouse is a bird found in arid regions and is known for its long, pointed tail feathers"}, 
{"The Golden-headed Cisticola is a small bird with a distinctive golden crown and is found in Africa"}, 
{"The Western Bluebird has bright blue plumage and is found in North America"}, 
{"The Long-tailed Duck has a distinct, long tail and is found in northern regions around the world"}, 
{"The Orange-bellied Parrot is one of the rarest parrot species, native to Australia"}, 
{"The Red-legged Partridge is a game bird with distinctive red legs and is native to parts of Europe"}, 
{"The Wilson's Snipe is known for its winnowing display during the breeding season"}, 
{"The Arctic Tern has the longest migratory journey, traveling from the Arctic to Antarctica"}, 
{"The Common Raven is known for its intelligence and complex vocalizations"}, 
{"The Cattle Egret is often found foraging near cattle, feeding on insects disturbed by their movement"}, 
{"The Black-throated Diver is a diving bird with a striking black throat and white plumage"}, 
{"The Greater Ani is a bird known for its communal nesting habits and distinctive calls"}, 
{"The Eurasian Crag Martin is a swift with a distinctive white rump and is found in rocky areas"}, 
{"The Spot-billed Toucanet is a small toucan with a distinctive spotted bill"}, 
{"The Eurasian Siskin has vibrant yellow plumage with black streaks and is found in Europe and Asia"}, 
{"The Blue-crowned Conure is a parrot with striking blue and green plumage and is native to South America"}, 
{"The Red-billed Blue Magpie is known for its long tail and vibrant blue and red plumage"}, 
{"The European Nightjar is a nocturnal bird with cryptic plumage, blending into its surroundings"}, 
{"The Olive-backed Sunbird is a small bird with iridescent green and yellow plumage"}, 
{"The Common Whitethroat is a warbler with a distinctive white throat and is found in Europe and Asia"}, 
{"The Broad-billed Tody is a colourful bird with a broad bill and is found in the Caribbean"}, 
{"The White-throated Dipper is a bird that bobs up and down while standing on rocks in fast-flowing streams"}, 
{"The Striped Manakin is known for its courtship displays involving rapid wing movements"}, 
{"The African Darter is a water bird with a long, slender neck and is found in sub-Saharan Africa"}, 
{"The Red-tailed Black Cockatoo has a distinctive red tail and is native to Australia"}, 
{"The Eurasian Bullfinch has a striking black cap and is found in Europe and Asia"}, 
{"The White-crowned Sparrow has distinctive black and white head stripes"}, 
{"The Variable Sunbird is a small bird with colourful plumage found in sub-Saharan Africa"}, 
{"The Eurasian Treecreeper is a small bird that climbs tree trunks in search of insects"}, 
{"The Black-throated Magpie-Jay is known for its loud calls and vibrant blue and white plumage"}, 
{"The White-winged Snowfinch is a bird adapted to alpine environments with white plumage"}, 
{"The Rose-ringed Parakeet is a parrot species with a distinctive rose-coloured ring around its neck"}, 
{"The Southern Ground Hornbill is known for its loud calls and is native to sub-Saharan Africa"}, 
{"The Yellow-throated Leaflove is a bird found in Africa with yellow plumage and a melodious song"}, 
{"The Slaty-backed Gull is a large gull with distinctive slate-grey plumage on its back"}, 
{"The Eurasian Blackcap has a melodic song and is known for its warbling calls"}, 
{"The Tawny Frogmouth is a nocturnal bird with cryptic plumage resembling tree bark"}, 
{"The Blue-throated Toucanet has a striking blue throat and is found in Central and South America"}, 
{"The Pacific Golden Plover is a migratory bird that travels long distances between its breeding and wintering grounds"}, 
{"The Buff-breasted Sandpiper is a shorebird with a buff-coloured breast and is found in the Americas"}, 
{"The American Avocet has a distinctive upturned bill and is known for its elegant wading behaviour"}, 
{"The Arctic Jaeger is a seabird known for its aggressive behaviour and kleptoparasitic tendencies"}, 
{"The Black-and-white Warbler is a small bird with bold black-and-white streaks on its plumage"}, 
{"The Crested Barbet is a bird with a distinctive spiky crest and is found in sub-Saharan Africa"}, 
{"The Green Heron is known for its ability to use bait to attract fish, dropping insects or other objects into the water to lure prey"}, 
{"The Violet-crowned Hummingbird is a striking hummingbird with vibrant violet and green plumage"}, 
{"The Sandhill Crane is known for its elaborate courtship dances, involving synchronised jumps and calls"}, 
{"The Common Myna is a highly adaptable bird with a remarkable ability to mimic human speech and other sounds"}, 
{"The Crested Guineafowl is a large bird with a distinctive, helmet-like crest on its head"}, 
{"The Tufted Titmouse is a small songbird known for its bold and curious behaviour"}, 
{"The Collared Kingfisher is a bird of prey known for its striking blue and white plumage"}, 
{"The Red-legged Honeycreeper is a small bird with bright blue and red plumage found in the Americas"}, 
{"The Eastern Yellow Wagtail is a migratory bird known for its yellow plumage and wagging tail"}, 
{"The Eurasian Bullfinch has a unique diet, feeding primarily on buds and young shoots"}, 
{"The Palm Warbler is a small songbird known for its habit of pumping its tail while foraging on the ground"}, 
{"The Steller's Jay is a colourful corvid with striking blue and black plumage found in western North America"}, 
{"The Great Cormorant is a diving bird known for its ability to swim underwater in search of prey"}, 
{"The White-faced Ibis is a wading bird with a distinctive white face and long, curved bill"}, 
{"The Yellow-headed Blackbird is known for its vibrant yellow head and loud, varied songs"}, 
{"The Eastern Towhee is a bird with striking black and rufous plumage and a distinctive 'drink-your-tea' call"}, 
{"The Masked Lapwing is a bird with a distinctive black and white facial mask and a loud, screeching call"}, 
{"The Grey Wagtail is a bird known for its distinctive undulating flight and yellow underparts"}, 
{"The Plain Chachalaca is a large bird with a loud and raucous vocalisation found in the Americas"}, 
{"The White-browed Coucal is a large, ground-dwelling bird with striking white markings on its face"}, 
{"The Common Chiffchaff is a small migratory bird known for its distinctive 'chiff-chaff' call"}, 
{"The Eurasian Spoonbill is a wading bird with a distinctive spoon-shaped bill used for feeding"}, 
{"The African Wood Owl is a nocturnal bird known for its haunting calls in sub-Saharan Africa"}, 
{"The Red-capped Plover is a shorebird with a striking red cap on its head and is found in Australia"}, 
{"The White-faced Whistling Duck is a bird with a distinctive white face and a whistling call"}, 
{"The Eurasian Blackbird is a songbird known for its melodic song and widespread distribution"}, 
{"The Eurasian Cuckoo is a brood parasite that lays its eggs in the nests of other bird species"}, 
{"The Mountain Bluebird is a thrush with striking blue plumage found in North America"}, 
{"The Eurasian Woodcock is a wading bird known for its cryptic plumage and aerial courtship displays"}, 
{"The European Pied Flycatcher is a migratory bird known for its black and white plumage"}, 
{"The Orange-breasted Sunbird is a small bird with vibrant orange and green plumage found in southern Africa"}, 
{"The Northern Waterthrush is a migratory songbird known for its habit of foraging in and around water"}, 
{"The Puna Ibis is a high-altitude bird with distinctive white plumage and a long, red bill"}, 
{"The Glossy Ibis is a wading bird with iridescent plumage and a distinctive long, curved bill"}, 
{"The Eurasian Bullfinch has a melodious song and is known for feeding on fruit buds"}, 
{"The Green-cheeked Amazon is a parrot with vibrant green plumage and a playful personality"}, 
{"The African Pygmy Kingfisher is a small, colourful bird with striking blue and orange plumage"}, 
{"The Eurasian Black Vulture is a large bird of prey known for its soaring flight"}, 
{"The Malachite Sunbird is a striking bird with vibrant green and blue plumage found in southern Africa"}, 
{"The Buff-throated Saltator is a songbird with a distinctive buff-coloured throat"}, 
{"The White-winged Tern is a migratory bird known for its striking black and white plumage"}, 
{"The Grasshopper Warbler is a small bird with a distinctive reeling song"}, 
{"The Orange-fronted Parakeet is a parrot with a bright orange forehead found in New Zealand"}, 
{"The Northern Bobwhite is a ground-dwelling bird known for its whistled 'bob-white' call"}, 
{"The Red-legged Seriema is a large bird with long legs and is known for its loud calls"}, 
{"The Great Tit is a small bird with striking black, white, and yellow plumage"}, 
{"The Hooded Oriole is a colourful bird with striking black and orange plumage found in the Americas"}, 
{"The Eurasian Oystercatcher is a bird with a distinctive long, orange bill and a loud 'piping' call"}, 
{"The Common Tern is a migratory bird with a graceful flight and distinctive black cap"}, 
{"The Violet-backed Starling is a bird with iridescent violet and black plumage found in Africa"}, 
{"The Black-bellied Whistling Duck is a duck species with a distinctive whistling call and black belly"}, 
{"The White-throated Kingfisher is known for its striking blue and white plumage and a loud, cackling call"}, 
{"The Eurasian Tree Sparrow is a small bird with a chestnut crown and is found in Europe and Asia"}, 
{"The Yellow-billed Hornbill is a bird with a long, down-curved bill and is native to sub-Saharan Africa"}, 
{"The Red-crowned Crane is one of the rarest cranes and is considered a symbol of longevity in Japan"}, 
{"The Australian White Ibis is a wading bird with a long, curved bill and is found in Australia"}, 
{"The Olive-sided Flycatcher is a bird with a distinctive 'quick-three-beers' song and is found in North America"}, 
{"The Glossy Swiftlet is a small, swift-flying bird with glossy black plumage found in Southeast Asia"}, 
{"The Oriental Magpie-Robin is a songbird with bold black and white markings and a melodious song"}, 
{"The African Skimmer is a bird with a unique feeding technique, skimming its lower mandible through water to catch fish"}, 
{"The Black-collared Starling is known for its striking black plumage with a contrasting white collar"}, 
{"The Sand Martin is a small swallow species that nests in burrows dug into sandbanks"}, 
{"The Toco Toucan has one of the largest bills relative to body size among all birds"}, 
{"The Eurasian Jay is known for its habit of caching foolised for future consumption"}, 
{"The Common Eider is a sea duck known for its soft down feathers, which are used to line its nest"}, 
{"The Yellow-bellied Sapsucker is a woodpecker species known for drilling holes in trees to feed on sap"}, 
{"The Western Osprey is a raptor specialised in catching fish and is found near bodies of water"}, 
{"The Blue-headed Vireo is a migratory songbird with a blue-grey head and distinctive facial markings"}, 
{"The Long-billed Curlew has an exceptionally long bill, used to probe in mud for invertebrates"}, 
{"The Northern Flicker is a woodpecker with a unique colour pattern and a distinctive, loud call"}, 
{"The White-crowned Hornbill is a bird with a large, downward-curved bill and a white crown"}, 
{"The Northern Pintail is a dabbling duck with a long, pointed tail and elegant plumage"}, 
{"The Cape Gannet is a seabird with striking black eye markings and is native to southern Africa"}, 
{"The Eurasian Penduline Tit is known for its unique nest, resembling a hanging sack made of plant fibres"}, 
{"The Azure-winged Magpie is a bird with vibrant blue and black plumage and is native to East Asia"}, 
{"The Olive Warbler is a small songbird with olive-green plumage and is found in North America"}, 
{"The Yellow-throated Vireo is a migratory bird with a bright yellow throat and a melodious song"}, 
{"The Laysan Albatross is known for its remarkable ability to cover vast distances during long-distance flights"}, 
{"The Dark-eyed Junco is a sparrow species with distinct plumage variations based on geographic location"}, 
{"The Chestnut-collared Longspur is a songbird with a chestnut-coloured collar and is found in North America"}, 
{"The Black-crowned Tchagra is a bird found in Africa with striking black and white plumage"}, 
{"The Northern Hawk Owl is a diurnal owl species known for its keen hunting abilities during daylight"}, 
{"The European Greenfinch is a songbird with vibrant green plumage and is found in Europe and Asia"}, 
{"The Straw-headed Bulbul is known for its melodious song and is native to Southeast Asia"}, 
{"The Fork-tailed Flycatcher is a bird with a distinctive forked tail and is found in the Americas"}, 
{"The Red-fronted Macaw is a parrot species with bright red plumage and is native to South America"}, 
{"The White-tailed Tropicbird has long tail streamers and is found in tropical oceans"}, 
{"The White-cheeked Barbet is a bird with a vibrant green body and distinctive white cheeks"}, 
{"The Red-winged Pigeon is known for its bright red patches on the wings and is found in Africa"}, 
{"The Little Tern is a small seabird with a distinctive black cap and is found worldwide"}, 
{"The Green Iora is a small bird with striking green and black plumage and is found in Southeast Asia"}, 
{"The Swainson's Thrush is a migratory songbird known for its flute-like song"}, 
{"The Marbled Godwit is a shorebird with a long, upturned bill and is found in the Americas"}, 
{"The Red-throated Diver is a diving bird with a distinctive red throat and is found in northern regions"}, 
{"The African Firefinch is a small bird with bright red plumage and is native to sub-Saharan Africa"}, 
{"The Broad-tailed Hummingbird is a migratory hummingbird with a distinctive buzzing sound during flight"}, 
{"The European Roller is known for its striking blue and orange plumage and is found in Europe and Asia"}, 
{"The Wilson's Warbler is a small songbird with bright yellow plumage and a black cap"}, 
{"The Yellow-crowned Bishop is a weaver bird with a bright yellow crown and is found in Africa"}, 
{"The Blue-faced Parrotfinch is a small finch with a vibrant blue face and is native to Australia"}, 
{"The Spectacled Owl is a nocturnal bird with striking facial markings that resemble spectacles"}, 
{"The Yellow-tufted Honeyeater is a bird with distinctive yellow tufts of feathers on its head, native to Australia"}, 
{"The Greater Yellowlegs is a shorebird with long, bright yellow legs and a distinctive call"}, 
{"The Common Nighthawk is a nocturnal bird known for its erratic flight and insect-catching abilities"}, 
{"The Blue-throated Hummingbird is a large hummingbird with vibrant blue throat feathers"}, 
{"The Indian Roller is the state bird of four Indian states and is known for its aerial acrobatics"}, 
{"The Eurasian Spoonbill has a unique feeding technique, sweeping its bill from side to side in shallow water"}, 
{"The Black-chinned Sparrow is a songbird with a black throat patch and is found in North America"}, 
{"The Slender-billed Gull is a gull species with a slender, slightly upturned bill"}, 
{"The White-cheeked Turaco is a bird with vibrant green and white plumage, native to Africa"}, 
{"The Fork-tailed Drongo is a songbird with a distinctive forked tail and is found in Africa and Asia"}, 
{"The Sooty Shearwater is a seabird known for its long-distance migratory flights across the world's oceans"}, 
{"The Blue-winged Teal is a dabbling duck with striking blue wing patches and a distinctive call"}, 
{"The Chestnut-backed Chickadee is a small songbird with a chestnut-coloured back, found in North America"}, 
{"The White-rumped Sandpiper is a shorebird with a distinctive white rump and is found in the Americas"}, 
{"The Elegant Crested Tinamou is a ground-dwelling bird with a distinctive crest on its head, native to South America"}, 
{"The Brown-headed Nuthatch is a small bird that often forages headfirst down tree trunks"}, 
{"The Red-winged Blackbird is a songbird with striking red and yellow shoulder patches"}, 
{"The Green Woodhoopoe is a bird with vibrant green and black plumage and is native to Africa"}, 
{"The Eurasian Reed Warbler is a migratory bird that breeds in Europe and winters in Africa"}, 
{"The Yellow-breasted Chat is a songbird with a bright yellow breast and a variety of complex vocalizations"}, 
{"The White-crowned Sparrow has a distinct white crown and is known for its clear, whistle-like song"}, 
{"The White-throated Needletail is a swift with distinctive white markings on its throat"}, 
{"The Ruppell's Vulture is a large vulture with a pale head and is native to sub-Saharan Africa"}, 
{"The Australian Shelduck is a large duck species with striking black and white plumage"}, 
{"The Common Hoopoe is a bird known for its distinctive 'crown' of feathers and is found in Europe, Asia, and Africa"}, 
{"The Purple Sunbird is a small bird with vibrant purple and iridescent plumage, native to South Asia"}, 
{"The Black-winged Stilt is a wading bird with long, thin legs and a distinctive black-and-white colour pattern"}, 
{"The Common Redpoll is a small finch with a red crown and is found in northern regions"}, 
{"The Piping Plover is a small shorebird with a distinctive piping call and is found in North America"}, 
{"The European Shag is a seabird with dark plumage and a distinctive crest on its head"}, 
{"The Orange Bishop is a weaver bird with bright orange plumage and is native to Africa"}, 
{"The Plain-coloured Tanager is a small bird with plain plumage, native to Central and South America"}, 
{"The Yellow-rumped Warbler is a migratory songbird with distinctive yellow patches on its rump"}, 
{"The White-eyed Vireo is a songbird with bright white eyes and a cheerful, melodious song"}, 
{"The Common Murre is a seabird with a distinctive black and white colour pattern and is found in the Northern Hemisphere"}, 
{"The White-throated Toucan is a large-billed toucan with a striking black and white colour pattern"}, 
{"The Eurasian Curlew is a large wading bird with a long, down-curved bill"}, 
{"The Greater Honeyguide is a bird known for its unique relationship with honey badgers, guiding them to beehives"}, 
{"The Blue Grosbeak is a songbird with striking blue and brown plumage, found in North and Central America"}, 
{"The White-winged Crossbill is a finch with a unique crossed bill adaptation for extracting seeds from conifer cones"}, 
{"The Whiskered Tern is a migratory bird with long, slender black whiskers and is found globally"}, 
{"The Black-crowned Waxbill is a small finch with a distinctive black crown and is native to Africa"}, 
{"The American Woodcock is a ground-dwelling bird known for its elaborate courtship displays"}, 
{"The Crested Francolin is a bird with a distinctive crest on its head and is found in Africa"}, 
{"The Ring-necked Pheasant is a game bird with colourful plumage and a distinctive white neck ring"}, 
{"The Yellow-fronted Canary is a small songbird with bright yellow plumage, native to Africa"}, 
{"The Eastern Whipbird is a bird with a distinctive 'whip' call and is found in Australia"}, 
{"The Great Antshrike is a bird with striking black and white plumage, native to South America"}, 
{"The Black Skimmer is a bird with a unique bill, longer on the lower mandible, used for skimming the water surface"}, 
{"The Eurasian Nuthatch is a small bird known for its habit of climbing down tree trunks headfirst"}, 
{"The Yellow-throated Sparrow is a songbird with a bright yellow throat and is found in Asia"}, 
{"The Long-tailed Cormorant is a bird with a long, slender tail and is native to Africa"}, 
{"The Eurasian Linnet is a small finch with a distinctive crimson forehead and breast"}, 
{"The Eurasian Hobby is a small falcon known for its swift, acrobatic flight"}, 
{"The Brown Pelican is a seabird known for its unique hunting behaviour, diving from the air to catch fish"}, 
{"The White-winged Chough is a bird with black plumage and distinctive white wing patches"}, 
{"The Chestnut-breasted Coronet is a hummingbird with vibrant chestnut-coloured plumage"}, 
{"The Sedge Warbler is a migratory songbird with a distinctive, melodious song"}, 
{"The Spot-billed Duck is a dabbling duck with a distinctive yellow patch on its bill"}, 
{"The Western Kingbird is a flycatcher with a white throat and distinctive yellow belly"}, 
{"The Pacific Swallow is a bird with long, pointed wings and a deeply forked tail"}, 
{"The Red-throated Pipit is a small bird with a red throat and is found in Europe and Asia"}, 
{"The White-headed Buffalo Weaver is a weaver bird with a distinctive white head"}, 
{"The Eurasian Bullfinch has a melodious song and is known for its colourful plumage"}, 
{"The White-rumped Shama is a songbird with a melodious and varied song, native to Southeast Asia"}, 
{"The Black-collared Thrush is a bird with striking black and white plumage"}, 
{"The Tricoloured Heron is a wading bird with distinctive blue-grey, white, and rust-coloured plumage"}, 
{"The Eurasian Golden Oriole is known for its striking yellow and black plumage"}, 
{"The African Grey Hornbill is a bird with a large, downward-curved bill and is native to Africa"}, 
{"The Yellow-faced Grassquit is a small finch with yellow facial markings, found in the Americas"}, 
{"The Sooty Falcon is a bird of prey with dark plumage and is found in the Middle East"}, 
{"The Little Green Bee-eater is a colourful bird with green plumage and a long, slender bill"}, 
{"The Eurasian Oystercatcher is a wading bird with a distinctive long, orange bill"}, 
{"The Brown-throated Wattle-eye is a small bird with a distinctive wattled eye marking"}, 
{"The Stilt Sandpiper is a shorebird with long, thin legs and is found in the Americas"}, 
{"The Spectacled Eider is a sea duck with a distinctive white eye patch"}, 
{"The Green-winged Pytilia is a finch with striking green and black plumage, found in Africa"}, 
{"The Bar-tailed Godwit is a migratory bird with a long bill and is known for its long-distance flights"}, 
{"The White-vented Myna is a bird with a distinctive white patch on its rump"}, 
{"The Eastern Whip-poor-will is a nocturnal bird known for its repetitive 'whip-poor-will' call"}, 
{"The European Stonechat is a bird named for its habit of perching on stones and other elevated spots"}, 
{"The Pied Wagtail is a bird with black and white plumage and a distinctive wagging tail"}, 
{"The Eastern Meadowlark is a songbird with bright yellow underparts and a melodic song"}, 
{"The Red-shouldered Vanga is a bird with striking red and black plumage, native to Madagascar"}, 
{"The European Goldfinch is a small finch with vibrant red, black, and yellow plumage"}, 
{"The Sulphur-crested Cockatoo is a large cockatoo with striking yellow crest feathers"}, 
{"The Eurasian Spoonbill is a wading bird with a distinctive spoon-shaped bill"}, 
{"The Blue Tit is a small bird with blue and yellow plumage and is found in Europe and Asia"}, 
{"The Common Ringed Plover is a shorebird with a distinctive black ring around its neck"}, 
{"The Eurasian Coot is a water bird known for its distinctive white frontal shield"}, 
{"The Blue-black Grassquit is a small finch with blue-black plumage, found in the Americas"}, 
{"The White-throated Magpie-Jay is known for its striking blue and white plumage"}, 
{"The Common Grackle is a songbird with iridescent plumage and is found in North America"}, 
{"The Rufous Treecreeper is a small bird that climbs tree trunks in search of insects"}, 
{"The Indian Robin is a bird with black and white plumage and is found in South Asia"}, 
{"The Green Hermit is a hummingbird with vibrant green plumage and a long, straight bill"}, 
{"The White-cheeked Starling is a bird with a distinctive white cheek patch"}, 
{"The Crested Lark is a songbird with a distinctive crest on its head, found in Europe and Asia"}, 
{"The Superb Fairywren is a small bird with striking blue and black plumage, native to Australia"}
};